QALI-125: List values for the Dashboard web widgets
qalipsis/qalipsis-oss pull request #129
Opened 2022-10-28 09:02 UTC by oceenachi

QALI-125: List values for the Dashboard web widgets

2022-11-03 07:44 UTC, ericjesse requested changes

2022-11-08 18:39 UTC, ericjesse requested changes

2022-11-08 18:39 UTC, ericjesse commented on head/src/main/kotlin/io/qalipsis/core/head/jdbc/repository/CampaignRepository.kt
> +    suspend fun aggregate(
```suggestion
    suspend fun retrieveCampaignsStatusHistogram(
```

2022-11-10 09:33 UTC, oceenachi commented on head/src/main/kotlin/io/qalipsis/core/head/report/WidgetServiceImpl.kt
> +        val minutes = if (timeOffset % 1 > 0) ((timeOffset % 1) * 100).roundToLong() else 0
@ericjesse a place with a time offset of 30 minutes, how is it represented. is it as 0.30 or 0.5. If it is 0.5 then it works

2022-11-10 09:49 UTC, ericjesse commented on head/src/main/kotlin/io/qalipsis/core/head/report/WidgetServiceImpl.kt
> +        val minutes = if (timeOffset % 1 > 0) ((timeOffset % 1) * 100).roundToLong() else 0
It will be 0.5, since the timeOffset is provided in hours.

2022-11-10 09:50 UTC, oceenachi commented on head/src/main/kotlin/io/qalipsis/core/head/report/WidgetServiceImpl.kt
> +        val minutes = if (timeOffset % 1 > 0) ((timeOffset % 1) * 100).roundToLong() else 0
okay

2022-11-14 07:39 UTC, ericjesse approved these changes

2022-11-14 12:10 UTC, merged