QALI-289 Create the zip and zipLast operators to join uncorrelated so…
qalipsis/qalipsis-oss pull request #133
Opened 2022-11-13 19:50 UTC by p-bril

…urces

2022-11-16 09:26 UTC, ericjesse requested changes

2022-11-16 09:26 UTC, ericjesse commented on factory/src/main/kotlin/io/qalipsis/core/factory/steps/zip/RightSources.kt
> +internal class RightSources<T : Any>(
```suggestion
internal class RightSource<T : Any>(
```

2022-11-16 09:26 UTC, ericjesse commented on factory/src/main/kotlin/io/qalipsis/core/factory/steps/zip/ZipStep.kt
> +                        coroutineScope.launch { channel.send(mapOf(record.stepName to record.value)) }
```suggestion
                        rightValues.send(record.value)
```

2022-11-16 09:26 UTC, ericjesse commented on factory/src/main/kotlin/io/qalipsis/core/factory/steps/zip/ZipStep.kt
> +        coroutineScope.launch {
```suggestion
```
You already are in a suspended scope, no need to start another coroutine in the present case.

2022-11-16 09:26 UTC, ericjesse commented on factory/src/main/kotlin/io/qalipsis/core/factory/steps/zip/ZipStep.kt
> +        @JvmStatic
```suggestion
```

2022-11-16 09:26 UTC, ericjesse commented on factory/src/main/kotlin/io/qalipsis/core/factory/steps/zip/ZipStep.kt
> +            context.send(outputSupplier(input, secondaryValues))
```suggestion
            context.send(input to secondaryValues)
```

2022-11-16 09:26 UTC, ericjesse commented on factory/src/main/kotlin/io/qalipsis/core/factory/steps/zipLast/ZipLastStep.kt
> +internal class ZipLastStep<I, O>(
Apply the changes proposed for the ZipStep.

2022-11-16 09:26 UTC, ericjesse commented on factory/src/main/kotlin/io/qalipsis/core/factory/steps/zip/ZipStep.kt
> +            latch.release()
```suggestion
```

2022-12-12 19:57 UTC, joval2 approved these changes
Please rebase this branch onto master and squash all your commits.

2022-12-12 19:57 UTC, joval2 commented on factory/src/main/kotlin/io/qalipsis/core/factory/steps/zipLast/ZipLastStep.kt
> + * Step to join flows from several [Step]s into a single one. While this steps technically has several
Why does this class have the same documentation with ZipStep ?

2022-12-13 05:28 UTC, joval2 approved these changes

2022-12-13 06:33 UTC, merged